name: CKAN instance
on: [push]
jobs:
  test:
    strategy:
      matrix:
        ckan-version: [2.9, 2.8, 2.7]
      fail-fast: false

    name: CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    services:
      ckan:
        image: openknowledge/ckan-dev:${{ matrix.ckan-version }}
        env:
          CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
          CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
          CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
          CKAN_SOLR_URL: http://solr:8983/solr/ckan
          CKAN_REDIS_URL: redis://redis:6379/1
          CKAN_DATAPUSHER_URL: http://datapusher:8800
          CKAN__DATAPUSHER__CALLBACK_URL_BASE: http://ckan:5000
          TZ: UTC
          CKAN_SYSADMIN_NAME: ckan_admin
          CKAN_SYSADMIN_PASSWORD: test1234
          CKAN_SYSADMIN_EMAIL: mail@example.com
        ports:
          - "5000:5000"
      solr:
        image: ckan/ckan-solr:${{ matrix.ckan-version }}
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      datapusher:
        image: ghcr.io/keitaroinc/datapusher:0.0.17
        environment:
          - DATAPUSHER_MAX_CONTENT_LENGTH=10485760
          - DATAPUSHER_CHUNK_SIZE=16384
          - DATAPUSHER_CHUNK_INSERT_ROWS=250
          - DATAPUSHER_DOWNLOAD_TIMEOUT=30
          - DATAPUSHER_SSL_VERIFY=False
      redis:
          image: redis:3

    steps:
    - uses: actions/checkout@v3
    - run: sleep 10
    - name: LOG BEFORE CKAN CHECK...
      run: docker logs "${{ job.services.ckan.id }}"
    - name: Check if CKAN is up
      run: |
        curl --retry 5 --retry-delay 1  http://localhost:5000/api/3/action/status_show
    - name: Generate CKAN API token
      run: |
        echo "TEST_API_KEY=$(docker exec "${{ job.services.ckan.id }}" ckan user token add ckan_admin dev_token | sed 's/API Token created://' | tr -d '\n\t')" >> $GITHUB_ENV
      if: matrix.ckan-version == '2.9'
    - name: Generate CKAN API key
      run: |
        echo "TEST_API_KEY"=$(docker exec "${{ job.services.ckan.id }}" paster --plugin=ckan user ckan_admin | grep -o -P '(?<=apikey=).*(?= created)') >> $GITHUB_ENV
      if: matrix.ckan-version != '2.9'
    - name: Get value of TEST_API_KEY
      run: |
        curl -H "Authorization: ${{ env.TEST_API_KEY }}" http://localhost:5000/api/3/action/user_show?id=ckan_admin
    - name: LOG AFTER CKAN CHECK...
      run: docker logs "${{ job.services.ckan.id }}"